name: "RandomForest"
scaler: "robust"
params:
  _target_: sklearn.ensemble.RandomForestRegressor
  n_estimators: 100
  max_depth: 10
  random_state: 42

# Grille de recherche pour GridSearchCV
search_space:
  model__n_estimators: [50, 100, 200]
  model__max_depth: [5, 10, 15, null]
  model__min_samples_split: [2, 5]